global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "applytrack-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8000
